name: ci

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - develop
    paths-ignore:
      - README.md

jobs:
  hello-world: # job id
    name: select os
    runs-on: macos-13
    steps:
      - name: check out
        uses: actions/checkout@v3
      - name: setup xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.1'
      - name: Decrypt provisioning profile
        run: |
          echo ${{ secrets.PROVISIONING_PROFILE }} | base64 --decode > profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          mv profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
      - name: set up
        run: make set_up
      - name: xcode clean build
        run: xcodebuild clean -project ScheduleManagements.xcodeproj
      - name: xcode build
        run: |
          xcodebuild -sdk iphonesimulator -configuration Debug -project ScheduleManagements.xcodeproj -scheme ScheduleManagements build
