name: CocoaPods

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CocoaPods
      run: |
        gem install cocoapods -v 1.12.1
        pod install

    - name: Build and Test
      run: xcodebuild -workspace ScheduleManagements.xcworkspace -scheme ScheduleManagements -destination "platform=iOS Simulator,OS=16.0,name=iPhone 15" build test
