name: XcodeBuildTest

on:
  push:
    branches:
      - develop
      - feature/add-actions-ios
jobs:
  hello-world: # job id
    name: select os
    runs-on: macos-13
    steps:
      - name: check out
        uses: actions/checkout@v2
      - name: setup xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3.1'
      - name: xcode build
        run: xcodebuild -project ScheduleManagements.xcodeproj -scheme ScheduleManagements -destination "platform=iOS Simulator,OS=16.0,name=iPhone 15" build
